org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.22
forge_version_range=[36,)
loader_version_range=[36,)

mod_id=compasstomap
mod_name=Compass to Map Legacy
mod_license=MIT
mod_version=1.0.0-1.16.5
mod_group_id=com.kuronami.compasstomap
mod_authors=KURONAMI, Qplop28
mod_description=Backport of Compass to Map for Forge 1.16.5. Detects Explorer's Compass results and sends JourneyMap-compatible waypoints.